### ISSUE TITLE
Kalman filter design issue in RTIMULib2

### ISSUE THREAD

**Issue by mgrouch** [HongshiTan/RTIMULib2#13]
I see the process model used in Kalman filter implementation in RTImuLib2 doesn't estimate biases. So it will only work for inputs without biases. 

Good Kalman filter process model should have biases of the sensors as state variables and estimate and eliminate them as it goes.

**Comment by HongshiTan** [comment]
Sensor bias is eliminated through calibration. RTIMULib2 includes calibration method for the accelerometer, gyroscope, and compass, which is should be applied before sensor fusion
