### ISSUE TITLE
CPP ellipsoid fit used instead of Octave code during calibration

### ISSUE THREAD

**Issue by flabrosse** [HongshiTan/RTIMULib2#4]
I was recently discovered that there is now a cpp calibration programme for the ellipsoid fit in this repo of RTIMULib2.  This is great news.

Is anybody working on using it instead of the Octave (matlab) code from the calibration functions?  I am happy to work on this but would prefer to avoid duplication of effort!

**Comment by HongshiTan** [comment]
Hi, there should some code in PX4 flight control, i.e. magnetometer calibration. For this repo, I was planning to integrate it, but quite busy now :)
